tinyMCE.addI18n('ru.yandexmaps_dlg',{
  title:"Insert/Edit Yandex Map",
  tab_general: "Main",
  dialog_title : "Yandex Map",
  map:"Map",
  error_geocoder:"Address was not found",
  search:"Search",
  change:"Change",
  options:"Options",
  size:"Size",
  pixel:"Pixel",
  position:"Position",
  address:"Address",
  coordinates:"Coordinates",
  coords:"Coordinates",
  height:"Height",
  width:"Width",
  map_type:"Map type",
  map_type_standard:"Standard",
  map_type_people:"People",
  baloon:"Balloon",
  baloon_title:"Title",
  baloon_descr:"Description",
  baloon_show:"show"
});
